-- AlterEnum
ALTER TYPE "ActividadTipo" ADD VALUE 'USUARIO_PASSWORD_CAMBIADO';
ALTER TYPE "ActividadTipo" ADD VALUE 'USUARIO_PASSWORD_RESETEADO';

-- AlterEnum
ALTER TYPE "EntidadTipo" ADD VALUE 'USUARIO';